@extends('user.layout.app')
 

@section('content')
<div class="row gray-section no-margin">
    <div class="container">
        <div class="content-block">
            <h2>{{ $title }}</h2>
            <div class="title-divider"></div>
            <p>
            Ces conditions (“conditions d'utilisation”) s'appliquent à votre visite et à votre utilisation de notre site web à l'adresse www.top-drivers.fr (“le site web”), au service et à l'application (comme définis ci-dessous), ainsi qu'à toutes les informations, recommandations et/ ou services qui vous sont fournis directement ou indirectement par le site web, le service et l'application. <br>

VEUILLEZ LIRE ATTENTIVEMENT CES CONDITIONS D'UTILISATION AVANT DE TELECHARGER NOTRE APPLICATION ET/ OU D'UTILISER NOTRE SERVICE.
Top Drivers <br>
Votre cocontractant est Top Drivers, Auto-entreprise établie en France, dont le siège se trouve 10 rue de Neuvic 67100 Strasbourg France, inscrite au CFE (centre de formalité des Entreprises )
<b> Services proposés par Top Drivers </b><br>
Top Drivers propose des informations et permet d'obtenir des services de transport offerts par ses propres chauffeurs ou par des tiers transporteurs, chauffeurs ou exploitants de parcs de véhicules ("le transporteur"). Ces services peuvent être demandés par le biais de l'utilisation d'une application fournie par Top Drivers, téléchargée et installée par vos soins sur votre téléphone portable (smartphone) ("l'application"). Tous les services fournis par Top Drivers par le biais de votre utilisation de l'application sont désignés ci-après par "le service".<br>
<b>Comment un contrat est-il conclu entre Top Drivers et vous ?</b> <br>
En utilisant l'application ou le service, vous concluez un contrat avec Top Drivers ("le contrat"). Pour pouvoir utiliser l'application ou le service, vous devez d'abord vous inscrire chez Top Drivers. Quand vous vous inscrivez, vous devez communiquer à Top Drivers vos informations à caractère personnel, votre numéro de téléphone mobile et les données de votre carte de crédit. Si votre inscription a été opérée avec succès chez Top Drivers, celle-ci vous fournira un compte personnel auquel vous pourrez accéder au moyen d'un mot de passe de votre choix.<br>
Vous devez être âgé d'au moins 18 ans pour pouvoir utiliser le service ou l'application. Si vous résidez dans une juridiction qui restreint l'utilisation du service ou de l'application pour des raisons d'âge, ou qui restreint la possibilité de nouer des contrats pour des raisons d'âge, vous devrez respecter ces limites d'âge et vous ne pourrez pas utiliser le service et l'application. Vous déclarez que si vous êtes une personne physique, vous avez l'âge légal nécessaire pour conclure un contrat contraignant, ou que si vous créez un compte pour une personne morale, vous êtes autorisé à agir de la sorte et à engager cette personne au regard de ces conditions d'utilisation, et à l'inscrire en vue d'utiliser le service et l'application.<br>
<b>Comment utiliser le service et l'application ? </b><br>
L'application vous permet d'envoyer une demande de service de transport à un transporteur (nos propres véhicules avec chauffeur ou tiers). Le récepteur GPS (qui doit être installé sur le téléphone portable (smartphone) sur lequel vous avez téléchargé l'application) détecte votre emplacement et envoie vos données de localisation au transporteur concerné. Le transporteur peut accepter ou refuser toute demande de service de transport, comme bon lui semble. Le transporteur est par ailleurs libre de décider d'utiliser ou non l'application pour recevoir les requêtes générées par le biais de l'application. Si le transporteur accepte une demande, l'application vous en avertit et vous communique des informations au sujet du transporteur (y compris son nom, le numéro d'immatriculation du véhicule et l'évaluation de son service à la clientèle) ainsi que la possibilité de contacter le transporteur par téléphone. L'application vous permet aussi de suivre la progression du transporteur vers le lieu de prise en charge, en temps réel.<br>
Top Drivers consentira des efforts raisonnables pour vous mettre en contact avec un transporteur afin d'obtenir des services de transport, en fonction de la disponibilité des transporteurs établis dans ou à proximité de votre région au moment de votre demande de services de transport.<br>
Pour éviter toute ambiguïté : Top Drivers est un fournisseur de services de transport et un intermédiaire; Certaines courses sont transmises à des transporteurs tiers. Il appartient au transporteur tiers d'offrir les services de transport qui peuvent être demandés par le biais de l'utilisation de l'application et/ ou du service. Dans ce dernier cas Top Drivers agit simplement en tant qu'intermédiaire entre le transporteur et vous. La prestation de services de transport par le transporteur est donc régie par le contrat (devant être) conclu entre vous et le transporteur. Top Drivers ne sera jamais une partie à ce contrat.
Votre utilisation de l'application ou du service<br>
Vous garantissez que les informations que vous communiquez à Top Drivers sont exactes et complètes. Top Drivers peut à tout moment vérifier les informations qui vous lui avez communiquées et refuser le service ou l'utilisation de l'application sans devoir motiver sa décision.<br>
Vous ne pouvez accéder au service qu'en utilisant des moyens autorisés. Il vous appartient de vérifier que vous téléchargez l'application adéquate à votre téléphone. Top Drivers décline toute responsabilité si votre téléphone portable n'est pas compatible ou si vous téléchargez une version de l'application inadéquate. Top Drivers se réserve le droit de mettre un terme au service et à l'utilisation de l'application si vous utilisez le service ou l'application avec un GSM incompatible ou interdit.<br>
En utilisant l'application ou le service, vous acceptez par ailleurs<br>
    de n'utiliser le service ou de ne télécharger l'application que pour votre seul usage personnel et de ne pas les revendre à un tiers ;<br>
de ne pas autoriser des tiers à utiliser votre compte ;<br>
de ne pas céder ou transférer autrement votre compte à toute autre personne physique ou morale ;<br>
de ne pas utiliser un compte sur lequel une personne autre que vous dispose de droits sans autorisation appropriée ;<br>
de ne pas utiliser le service ou l'application à des fins illégales, notamment pour envoyer ou sauvegarder des contenus illégaux ou à des fins frauduleuses ;<br>
de ne pas utiliser le service ou l'application afin de nuire, d'embarrasser ou de déranger des tiers ;<br>
de ne pas compromettre le bon fonctionnement du réseau ;<br>
de ne pas perturber le service ou l'application d'une quelconque façon ;<br>
de ne pas copier ou distribuer l'application ou tout autre contenu de Top Drivers sans autorisation écrite de celle-ci ;<br>
de veiller à la fiabilité et à la confidentialité du mot de passe de votre compte ou de tout identifiant fourni par nos soins et permettant d'accéder au service et à l'application ;<br>
de nous faire parvenir une preuve d'identité que nous pourrions raisonnablement vous demander ;<br>
de n'utiliser un point d'accès ou un compte de données 3G (AP) que si vous y êtes autorisé ;<br>
que vous savez qu'en demandant des services de transport par SMS (en cas de disponibilité dans votre région), vous devrez acquitter des frais de messagerie standard ;<br>
de ne pas utiliser le service ou l'application avec un GSM incompatible ou interdit ;<br>
de respecter toute la législation applicable de votre pays d'origine, du pays, de l'état et/ ou de la ville où vous vous trouvez quand vous utilisez l'application ou le service.<br>
Top Drivers se réserve le droit de mettre immédiatement un terme au service et à l'utilisation de l'application si vous ne respectez pas l'une des règles énoncées ci-dessus.
<br>Paiement<br>
L'utilisation de l'application et du service est gratuite. Top Drivers se réserve le droit de demander une redevance pour l'utilisation de l'application et/ ou du service. Si Top Drivers décide d'appliquer une telle redevance, Top Drivers vous en avertira et vous permettra de poursuivre ou de résilier le contrat.<br>
Les tarifs pratiqués par le transporteur pour les services de transport sont indiqués sur le site web et peuvent être consultés par le biais de l'application. Ils peuvent être modifiés ou actualisés par Top Drivers de temps en temps. Il vous appartient de rester informé des tarifs actuels des services de transport.<br>
Top Drivers vous facturera les services de transport qui vous sont fournis par le transporteur, pour celui-ci. Vous acceptez de payer tous les services de transport que vous achetez au transporteur. Vous reconnaissez que Top Drivers peut débiter votre compte de carte de crédit que vous avez communiqué lors de votre inscription au service, pour les services de transport que vous avez demandés dans le cadre de votre compte (y compris les taxes et les pénalités de retard éventuelles). Vous êtes responsable du paiement en temps opportun de toutes les sommes dues. Vous devez indiquer à Top Drivers un compte de carte de crédit valide pour le paiement de toutes les sommes dues à tout moment. Les paiements effectués ne sont pas remboursables.<br>
Top Drivers utilise un système de paiement tiers (“le système de paiement”) pour associer votre compte de carte de crédit à l'application et au service. Le traitement des paiements ou des crédits éventuels découlant de votre utilisation de l'application et du service sera régi par les conditions et la politique de confidentialité du système de paiement et par les conditions de l'émetteur de votre carte de crédit, en plus de ces conditions d'utilisation. Top Drivers décline toute responsabilité en cas d'erreur due au système de paiement. Dans le cadre de votre utilisation du service, Top Drivers obtiendra certains détails des transactions, qu'elle utilisera conformément à ses déclarations en matière de confidentialité et de cookies.<br>
Indemnisation<br>
En acceptant ces conditions d'utilisation et en utilisant l'application ou le service, vous acceptez de défendre, d'indemniser et de garantir Top Drivers, ses filiales, ses concédants et chacun de ses dirigeants, administrateurs, autres utilisateurs, employés, mandataires et agents contre les réclamations, frais, dommages, pertes, engagements et dépenses (y compris les honoraires et les frais d'avocats) découlant de ou en rapport avec :<br>
    une violation des dispositions de ces conditions d'utilisation ou de toute législation ou réglementation applicable, visée ou non dans les présentes, dont vous vous rendriez coupable ;
une violation de droits de tiers, y compris les transporteurs contactés via l'application ;
l'utilisation ou une utilisation frauduleuse de l'application ou du service, dont vous vous rendriez coupable.
<br>Responsabilité<br>
Les informations, recommandations et/ ou services qui vous sont fournis directement ou indirectement par le site web, le service et l'application, ne constituent que des informations générales et non pas des avis. Top Drivers s'efforcera de maintenir le site web, l'application et leurs contenus dans un état correct et actualisé, mais ne garantit pas que le site web et/ ou l'application (et leurs contenus) sont exempts d'erreurs, de défauts, de logiciels malveillants ou de virus, ou que le site web et/ ou l'application sont corrects, actualisés et exacts.
Top Drivers ne sera pas responsable d'éventuels dommages découlant de l'utilisation (ou de l'incapacité à utiliser) le site web ou l'application (sauf en cas de décès ou de dommages corporels), y compris des dommages causés par des logiciels malveillants, des virus ou par une quelconque inexactitude ou omission d'informations, du site web ou de l'application, sauf si les dommages découlent d'un acte délibéré ou d'une grave négligence de Top Drivers.
Par ailleurs, Top Drivers ne sera pas responsable des dommages découlant de l'utilisation (ou de l'incapacité à utiliser) des moyens électroniques de communication avec le site web ou l'application, notamment les dommages découlant d'un échec ou d'un retard de transmission de communications électroniques, d'une interception ou d'une manipulation de communications électroniques par des tiers ou par des programmes informatiques utilisés pour des communications électroniques et la transmission de virus.<br>
Sans préjudice de ce qui précède et dans la mesure où c'est permis par la législation applicable, la responsabilité globale de Top Drivers n'excédera jamais un montant de 500 EUR ou, le cas échéant, l'équivalent de ce montant dans la devise que vous utilisez pour le paiement des services de transport au transporteur.
La qualité des services de transport demandés par le biais de l'utilisation de l'application ou du service relève entièrement de la responsabilité du transporteur qui vous fournit les services de transport. Top Drivers décline toute responsabilité dans le cadre des services de transport fournis par le transporteur ou en ce qui concerne des actes, actions, comportements, attitudes, et/ ou négligences du transporteur. Toute réclamation au sujet des services de transport fournis par le transporteur devra par conséquent être adressée à celui-ci.
Octroi de licence, restrictions et droit d'auteur
Les définitions suivantes s'appliquent dans le cadre de ces conditions d'utilisation.
“Contenu” désigne tout contenu présenté ou affiché, notamment des logos, icônes, marques de commerce, textes, légendes, images, photographies, images en mouvement, sons, illustrations, musique, logiciels (sauf l'application), opinions, remarques, commentaires, graphisme, liens, questions, suggestions, informations ou autres matériels.<br>
“Contenu de Top Drivers” désigne un contenu possédé ou utilisé par Top Drivers, ses filiales ou ses concédants et rendu disponible par le biais du site web, du service ou de l'application, y compris les contenus concédés sous licence par des tiers, mais pas les contenus d'utilisateurs.
“Utilisateur” désigne une personne qui accède au service ou à l'application ou les utilise.
“Contenu d'utilisateur” désigne un contenu qu'un utilisateur poste, envoie au serveur, publie, soumet ou transmet pour le rendre disponible sur le site web ou par le biais du service ou de l'application.
“Contenu collectif” désigne, collectivement, un contenu de Top Drivers et un contenu d'utilisateur.
A condition que vous respectiez ces conditions d'utilisation, Top Drivers vous accorde une licence limitée, non exclusive et incessible qui vous permet de :
    voir, télécharger et imprimer tout contenu de Top Drivers, uniquement pour votre utilisation personnelle et non commerciale ;<br>
voir tout contenu d'utilisateur auquel vous êtes autorisé à accéder, uniquement pour votre utilisation personnelle et non commerciale. Vous ne pouvez pas concéder les droits de licence accordés dans ce chapitre, en accordant une sous-licence.
Vous ne pouvez pas utiliser, copier, adapter, modifier, créer des œuvres dérivées, distribuer, concéder sous licence, vendre, céder, afficher ou présenter en public, reproduire, transmettre, transférer sous forme de flux, diffuser ou exploiter de toute autre manière le site web, le service, l'application ou des contenus collectifs, sauf si c'est expressément permis dans ces conditions d'utilisation. Vous ne pouvez pas réutiliser des contenus collectifs sans autorisation écrite préalable de Top Drivers. Aucune licence et aucun droit ne vous sont accordés tacitement ou autrement au regard de droits de propriété intellectuelle détenus ou contrôlés par Top Drivers ou ses concédants, sauf les licences et les droits expressément accordés dans ces conditions d'utilisation.
Octroi de licence par l'utilisateur
Nous pouvons, comme bon nous semble, permettre aux utilisateurs de poster, envoyer au serveur, publier, soumettre ou transmettre des contenus d'utilisateurs sur le site web ou par le biais du service ou de l'application. Les contenus d'utilisateurs seront considérés comme non confidentiels et communs. Par conséquent, Top Drivers disposera du droit non exclusif, sans redevance, d'utiliser, copier, distribuer et divulguer à des tiers tout contenu d'utilisateur à toutes fins, par tout moyen et dans le monde entier (“octroi de licence”).
Vous reconnaissez que Top Drivers agit comme un service de transport de personne et comme un simple intermédiaire pour la distribution de contenus d'utilisateurs et n'est pas responsable envers vous ou un quelconque tiers des contenus ou de l'exactitude des contenus d'utilisateurs. Top Drivers ne contrôlera pas en permanence les contenus d'utilisateurs que vous publiez et ne jouera pas un rôle de modérateur entre utilisateurs. En outre, Top Drivers ne sera pas tenue de le faire. Sans limitation de ce qui précède, vous reconnaissez et acceptez que les remarques, opinions, commentaires, suggestions et autres informations exprimés ou inclus dans des contenus d'utilisateurs ne reflètent pas nécessairement les points de vue de Top Drivers.
Vous utilisez les contenus d'utilisateurs entièrement à vos risques. Vous déclarez et garantissez que les contenus d'utilisateurs que vous postez ou que vous transmettez proviennent de vous et ne sont pas des plagiats de créations de tiers ou ne violent pas autrement de droits de propriété intellectuelle de tiers, de droits à la vie privée ou de droits de la personnalité, et qu'ils ne contiennent pas de propos diffamatoires ou désobligeants. Par ailleurs, vous déclarez et garantissez que vous êtes habilité à accorder la licence visée dans ce paragraphe.
Vous acceptez de garantir en permanence Top Drivers, ses filiales et ses concédants contre l'ensemble des frais, dépenses, dommages, pertes et engagements encourus ou subis par Top Drivers ou ses sociétés liées à cause d'un contenu d'utilisateur que vous avez posté ou transmis ou de votre utilisation du site web, du service ou de l'application.
Top Drivers se réserve le droit, comme bon lui semble, de bloquer ou de supprimer (en tout ou en partie) un contenu d'utilisateur que vous avez posté ou transmis, si Top Drivers estime qu'il n'est pas conforme à ces conditions d'utilisation (y compris les matériels qui violent ou sont susceptibles de violer des droits de propriété intellectuelle, des droits à la vie privée ou des droits de la personnalité de tiers), ou qu'il est inacceptable pour toute autre raison.
Vous acceptez d'avertir Top Drivers par écrit dans les plus brefs délais si un contenu d'utilisateur enfreint ces conditions d'utilisation. Vous acceptez de communiquer à Top Drivers des informations suffisantes pour lui permettre de vérifier si ce contenu d'utilisateur enfreint ces conditions d'utilisation. Top Drivers accepte de consentir des efforts raisonnables pour examiner une telle réclamation. Top Drivers pourra décider de prendre ou non une telle mesure, comme bon lui semble. Cependant, Top Drivers ne garantit ou ne déclare pas qu'elle bloquera ou supprimera (en tout ou en partie) le contenu d'utilisateur en question.
Octroi de licence pour l'application
Si vous respectez ces conditions d'utilisation, Top Drivers vous accorde une licence limitée, non exclusive et incessible qui vous permet de télécharger et d'installer une copie de l'application sur un téléphone portable que vous possédez ou contrôlez, et d'utiliser cette copie de l'application à titre personnel uniquement.
<br>Vous ne pourrez pas <br>
    accorder de licence ou de sous-licence, vendre, revendre, transférer, céder, distribuer ou exploiter commercialement d'une autre manière ou mettre à la disposition de tiers le service ou l'application d'une quelconque façon ;<br>
modifier le service ou l'application ou en créer des dérivés ;<br>
créer des liens électroniques vers le service ou placer des trames ou des miroirs d'une quelconque application sur tout autre serveur ou appareil sans fil ou basé sur l'Internet ;<br>
rétroconcevoir ou accéder à l'application afin de
concevoir ou construire un produit ou un service concurrent ;<br>
concevoir ou construire un produit en utilisant des idées, caractéristiques, fonctions ou images similaires du service ou de l'application ;<br>
copier des idées, caractéristiques, fonctions ou images du service ou de l'application ;
lancer un programme ou un script automatisé, notamment des logiciels robots, robots d'exploration, robots web, fureteurs web, indexeurs web, zombies, virus ou vers, ou tout programme susceptible d'adresser de multiples demandes par seconde à un serveur ou de compliquer ou entraver de façon intempestive le fonctionnement et/ ou les performances du service ou de l'application.
<br>Vous ne pourrez pas<br>
    envoyer ou sauvegarder des messages non sollicités ou répétitifs, en violation de la législation applicable ;
envoyer ou sauvegarder des contenus infractionnels, obscènes, menaçants, diffamatoires ou autrement illégaux ou délictuels, y compris des contenus préjudiciables envoyés à des enfants ou violant le droit à la vie privée de tiers ;<br>
envoyer ou sauvegarder des contenus contenant des virus, vers, chevaux de Troie ou autres codes informatiques, fichiers, scripts, agents ou programmes nuisibles ;<br>
entraver ou interrompre l'intégrité ou le bon fonctionnement du site web, de l'application ou du service ou des données qu'ils contiennent ;<br>
tenter d'accéder frauduleusement au site web, à l'application ou au service ou aux systèmes ou réseaux qui les supportent.<br>
Top Drivers aura le droit d'examiner les violations évoquées ci-dessus, dans toute la mesure permise par la loi, et d'engager des poursuites judiciaires. Top Drivers peut faire appel aux autorités policières et coopérer avec elles afin de poursuivre les utilisateurs qui violent ces conditions d'utilisation. Vous reconnaissez que Top Drivers n'est pas obligée de contrôler votre accès au site web, au service, à l'application ou aux contenus collectifs et l'utilisation que vous en faites, ou de vérifier ou d'éditer les contenus collectifs, mais qu'elle a le droit de le faire pour exploiter le site web, l'application et le service, pour s'assurer que vous respectez ces conditions d'utilisation ou pour respecter la législation applicable ou une injonction ou une demande d'un tribunal, d'une instance administrative ou d'un autre organe officiel. Top Drivers se réserve le droit d'annuler ou de désactiver, à tout moment et sans avis préalable, l'accès à un quelconque contenu collectif si elle estime qu'il enfreint ces conditions d'utilisation ou porte atteinte autrement au site web, au service ou à l'application.<br>
Politique en matière de droit d'auteur
Top Drivers respecte la législation en matière de droit d'auteur et attend de ses utilisateurs qu'ils s'y conforment aussi. Top Drivers entend écarter, dans certaines circonstances, les utilisateurs ou autres titulaires de comptes qui violent ou sont soupçonnés de violer (à plusieurs reprises) les droits d'auteur de tiers. Veuillez consulter la politique d'Top Drivers en matière de droit d'auteur à l'adresse https://www.top-drivers.fr pour de plus amples informations.
Droits de propriété intellectuelle
Top Drivers (ainsi que ses concédants, le cas échéant) détient seule tous les droits, titres et intérêts, y compris tous les droits de propriété intellectuelle liés, dans et sur le site web, l'application et le service, et les suggestions, idées, demandes d'amélioration, commentaires, recommandations et autres informations que vous ou toute autre partie communiquez au sujet du site web, de l'application ou du service.
Ces conditions d'utilisation ne constituent pas une vente et ne vous confèrent aucun droit de propriété direct ou indirect sur le site web, l'application ou le service, et aucun droit de propriété intellectuelle détenu par Top Drivers. Le nom, le logo et les dénominations de produits de Top Drivers associés à l'application et au service sont des marques de commerce de Top Drivers, de ses sociétés liées ou de tiers. Top Drivers n'accorde aucun droit ou aucune licence d'utilisation de ces marques.
Application provenant d'App Store<br>
En ce qui concerne les applications consultées ou téléchargées sur l'App Store d'Apple (“applications provenant d'App Store”), vous utiliserez uniquement ces applications :
    sur un produit vendu sous la marque Apple qui est équipé d'iOS (le système d'exploitation Apple) ;
comme permis par les Règles d'utilisation énoncées dans les conditions de service d'App Store. Top Drivers se réserve tous les droits sur l'application qui ne vous sont pas expressément conférés dans le cadre de ces conditions d'utilisation.<br>
Vous reconnaissez et acceptez que
    ces conditions d'utilisation s'appliquent uniquement entre vous et Top Drivers, et ne concernent pas Apple ;
Top Drivers, et pas Apple, est seule responsable des applications provenant d'App Store et de leurs contenus. Votre utilisation d'applications provenant d'App Store doit être conforme aux conditions de service d'App Store.
Vous reconnaissez qu'Apple n'est aucunement tenue de fournir une quelconque maintenance ou des services d'assistance pour les applications provenant d'App Store.
Si les applications provenant d'App Store ne sont pas conformes à une quelconque garantie applicable, vous pouvez en avertir Apple, qui vous remboursera, le cas échéant, le prix d'achat des applications provenant d'App Store et, dans la plus large mesure permise par la législation applicable, Apple n'aura aucune autre obligation de garantie pour les applications provenant d'App Store. En l'occurrence, les autres réclamations, pertes, engagements, dommages, frais ou dépenses éventuels imputables au manque de conformité à une quelconque garantie relèveront de la seule responsabilité de Top Drivers.<br>
Vous et Top Drivers reconnaissez que, dans les rapports entre Top Drivers et Apple, Apple décline toute responsabilité en cas de réclamation que vous ou un tiers pourriez introduire au sujet d'applications provenant d'App Store ou de votre possession et de votre utilisation d'applications provenant d'App Store, notamment :
    une réclamation portant sur la responsabilité du fait des produits ;
une réclamation selon laquelle les applications provenant d'App Store ne sont pas conformes à une exigence légale ou réglementaire applicable ;<br>
une réclamation introduite dans le cadre de la législation sur la protection des consommateurs ou d'une législation similaire.<br>
Vous et Top Drivers reconnaissez que si un tiers prétend que les applications provenant d'App Store ou votre possession et votre utilisation de ces applications provenant d'App Store violent ses droits de propriété intellectuelle, Top Drivers, et pas Apple, sera seule responsable des investigations, de la défense, du règlement et de l'abandon d'une telle plainte pour violation de propriété intellectuelle, dans la mesure requise par ce contrat.
Vous et Top Drivers reconnaissez et admettez qu'Apple et ses filiales sont des tiers bénéficiaires dans le cadre de votre licence d'utilisation des applications provenant d'App Store et que, dès que vous aurez accepté ces conditions d'utilisation, Apple aura le droit (et sera censée avoir accepté le droit) de faire appliquer les droits qui s'appliquent dans le cadre de ces conditions d'utilisation à votre licence d'utilisation des applications provenant d'App Store, en ce qui vous concerne en tant que tiers bénéficiaire.
Sans limitation des autres dispositions de ces conditions d'utilisation, vous devez respecter toutes les conditions de tiers applicables quand vous utilisez des applications provenant d'App Store.
Interactions avec des tiers<br>
Lors de l'utilisation du site web, de l'application et du service, des liens menant à des sites web possédés et contrôlés par des tiers peuvent être fournis de temps en temps, pour vous permettre d'entrer en contact avec ces tiers, d'acheter leurs marchandises ou leurs services, de participer à leurs promotions. Ces liens vous font sortir du site web, de l'application et du service et ne sont pas contrôlés par Top Drivers.
Lors de l'utilisation du site web, de l'application et du service, vous pouvez contacter, acheter des marchandises et/ ou des services ou participer à des promotions de tiers fournisseurs de services, annonceurs ou sponsors qui présentent leurs produits et/ ou leurs services par le biais d'un lien placé sur le site web, de l'application ou du service. Ces liens vous font sortir du site web, de l'application et du service et ne sont pas contrôlés par Top Drivers. Vous pouvez accéder à ces sites web grâce aux liens, afin de connaître leurs propres conditions et leur politique de confidentialité. Top Drivers n'est pas responsable et ne peut pas être tenue pour responsable des contenus et des activités de ces sites web. Par conséquent, vous visitez ces sites web et vous y accédez totalement à vos risques.
Veuillez noter que ces autres sites web peuvent envoyer leurs propres cookies aux utilisateurs, collecter des données ou demander des informations à caractère personnel. Nous vous conseillons donc de vérifier les conditions d'utilisation ou la politique de confidentialité de ces sites web avant de les utiliser.
Durée et cessation du contrat<br>
Le contrat est conclu entre Top Drivers et vous pour une durée indéterminée.
Vous pouvez résilier le contrat à tout moment en supprimant définitivement l'application installée sur votre smartphone, c'est-à-dire en désactivant votre possibilité d'utilisation de l'application et du service. Vous pouvez clôturer votre compte d'utilisateur à tout moment en suivant les instructions qui figurent sur le site web de Top Drivers.<br>
Top Drivers peut résilier le contrat à tout moment, avec effet immédiat (en désactivant votre possibilité d'utilisation de l'application et du service)
    si vous enfreignez l'une de ces conditions d'utilisation ;
si Top Drivers estime que vous utilisez l'application ou le service de façon abusive. Top Drivers n'est pas tenue de vous avertir à l'avance de la résiliation du contrat. Après la résiliation, Top Drivers vous en avertira conformément à ces conditions d'utilisation.
Nullité d'une ou de plusieurs dispositions
La nullité de l'une de ces conditions d'utilisation n'affectera pas la validité des autres dispositions de ces conditions d'utilisation.<br>
Si et dans la mesure où l'une de ces conditions d'utilisation est nulle ou inacceptable compte tenu des circonstances, conformément aux critères de caractère raisonnable et d'équité, elle sera remplacée par une disposition acceptable compte tenu de toutes les circonstances, qui correspond le plus possible à l'esprit de la condition nulle, en tenant compte du contenu et de l'objectif de ces conditions d'utilisation.
Modification du service et des conditions d'utilisation
Top Drivers se réserve le droit, comme bon lui semble, de modifier ou de remplacer l'une de ces conditions d'utilisation, ou de modifier, suspendre ou cesser à tout moment le service ou l'application (notamment la disponibilité d'une caractéristique, d'une base de données ou d'un contenu), en publiant un avis sur le site web ou en vous envoyant un avis par le biais du service, de l'application ou par courriel. Top Drivers peut aussi imposer des limites pour certaines caractéristiques et certains services, ou restreindre totalement ou partiellement votre accès au service sans vous en avertir et en déclinant toute responsabilité.
Avis<br>
Top Drivers peut avertir les utilisateurs par le biais d'un avis général, via le service ou l'application, ou par courriel envoyé à votre adresse électronique qui figure dans les données de comptes de Top Drivers, ou par courrier ordinaire envoyé à l'adresse postale figurant dans les données de comptes de Top Drivers.
Cession<br>
Vous ne pouvez pas céder vos droits dans le cadre de ces conditions d'utilisation sans autorisation écrite préalable de Top Drivers.<br>
Déclaration en matière de confidentialité et de cookies
Top Drivers collecte et traite les informations à caractère personnel des visiteurs du site web et des utilisateurs de l'application conformément à la déclaration en matière de confidentialité et de cookies Top-drivers.fr.<br>
Législation applicable et règlement des litiges<br>
Ces conditions d'utilisation sont régies par la législation de France. Les litiges, réclamations ou contestations découlant ou survenant dans le cadre de ces conditions d'utilisation ou de leur violation, de leur cessation, de leur mise en application, de leur interprétation ou de leur validité ou de l'utilisation du site web, du service ou de l'application (collectivement, “litiges”) seront tranchés exclusivement par le tribunal compétent de Strasbourg, France, sauf si vous signalez à Top Drivers dans le mois qui suit l'invocation de son droit d'engager une procédure judiciaire à Amsterdam, Pays-Bas, que cette disposition lui confère, que vous demandez le règlement du litige, de la réclamation ou de la contestation devant le tribunal compétent le plus proche. </p>
        </div>
    </div>
</div>
@endsection